# Generated by Django 5.1.6 on 2025-07-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0002_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada')], max_length=20)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.pago')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.reserva')),
            ],
        ),
    ]
